from yacs.config import CfgNode as CN

_C = CN()
_C.MODEL = CN()
_C.MODEL.BACKBONE = 'normal'
_C.MODEL.UPSAMPLE_TYPE = 'deconv'

_C.DATASET = CN()
_C.DATASET.TRAIN_IMAGES_DIR = ''
_C.DATASET.GT_IMAGES_DIR = ''


_C.TRAIN = CN()
_C.TRAIN.EPOCH_MAX = 4000
_C.TRAIN.PATCH_SIZE = 512
_C.TRAIN.CHECKPOINT_DIR = ''
_C.TRAIN.SAVE_INTERVAL = 100
_C.TRAIN.RESULTS_DIR = ''
_C.TRAIN.LEARNING_RATE = 1e-4
_C.TRAIN.LR_STEP = [2000, 3000]
_C.TRAIN.RESUME = ''

_C.TEST = CN()
_C.TEST.CHECKPOINT = ''
_C.TEST.RESULTS_DIR = ''

_C.GPU_ID = 0
