MODEL:
  BACKBONE: 'light_resiual'
  UPSAMPLE_TYPE: 'bilinear'

DATASET:
  TRAIN_IMAGES_DIR: './dataset/Sony/short/'
  GT_IMAGES_DIR: './dataset/Sony/long/'


TRAIN:
  CHECKPOINT_DIR: './sony_light_resiual_bilinear_model_checkpoint/'
  RESULTS_DIR: './sony_light_resiual_bilinear_model_train_results/'

TEST:
  RESULTS_DIR: './sony_light_resiual_bilinear_model_test_results/'

GPU_ID: 0